title: My personal blog - David Ren
email: 564867719r@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://keyitotallyojbk.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: David Ren # add your name
author-pic: adam-face.jpg
about-author: Hi, this is David Ren, I'm now a undergraduate in Beijing Institute of Technology, China, hope you enjoy my blog!

# Contact links
email: # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: artemsheludko # Add your Github handle
twitter: '@artemsheludko_' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]

links:
 - name:         Home
   url:          /
   external:     false
 - name:         About
   url:          /about
   external: false

links1:
  - name:	All
    url:	/
    type:	recent
    external:	false
  - name:	Profile
    url:	/blog/profile
    type:	profile
    external:	false
  - name:	Education background
    url:	/blog/EduBkg
    type:	EduBkg
    external:	false
  - name:	Research background
    url:	/blog/ResBkg
    type:	ResBkg
    external:	false
  - name:	My Love
    url:	/blog/MyLove
    type:	MyLove
    external:	false

blog_0:    recent
blog_1:	   profile
blog_2:    EduBkg
blog_3:    ResBkg
blog_4:    MyLove